config/routes.rb
Wir2::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations", 
                                      :omniauth_callbacks => "users/omniauth_callbacks"},
                     :path => '', :path_names => {:sign_in => "login", :sign_out => "logout",
                                                  :sign_up => "register"}

  devise_scope :user do
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "register", :to => "users/registrations#new"
    get "delete", :to => "users/registrations#destroy"
    get "settings", :to => "users/registrations#edit"
    get "settings/password", :to=> "users/registrations#password"
    get "settings/privacy", :to=> "users/registrations#privacy"
    get "search", :to=> "users#search"
    match '/search', to: 'users#search'
    get "profile", :to =>  "users#show"
  end 

  resources :users do
    member do
      get :follow
      get :unfollow
      get :unpend
      get :make_public
      get :make_private
    end
  end

  resources :notifications
  
  resources :pages
  resources :stories do
    member do
      get :vote_up
      get :vote_down
      get :unvote
      get :comment
    end
  end

  resources :comments
  resources :votes
  resources :relationships, only:[:create, :destroy]
  
  root :to => "pages#home"

  get '/about', to: 'pages#about'











end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  admin                  :boolean          default(FALSE)
#  username               :string(255)
#  firstname              :string(255)
#  lastname               :string(255)
#  sex                    :string(255)
#  dob                    :datetime
#  bio                    :string(255)
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base

  include PgSearch
  pg_search_scope :user_search, :against => [:username, :email],
                                :using => {
                                  tsearch: {:dictionary => 'simple', :prefix => true}
                                }
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  acts_as_voter

  acts_as_follower_plus
  acts_as_followable_plus

  has_many :notifications, :as => :notifiable
  
  
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model,
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username,
                  :sex, :name, :dob, :bio, :avatar, :country_name, :website, :location, 
                  :login, :private_followable, :provider, :uid, :admin, :profilepic

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  has_attached_file :avatar, styles: {xsml: "30x30#", thumb: "50x50#", small: "100x100#", 
                                      med:"350x350#", large:"1500x1500>"},
                    default_url: "/assets/no-image.png",
                    url:  "/assets/images/users/:id/album/:style/:basename.:extension",
                    path: ":rails_root/public/assets/images/users/:id/album/:style/:basename.:extension"

  has_many :stories, dependent: :destroy
  # has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  # has_many :followed_users, through: :relationships, source: :followed
  # has_many :reverse_relationships, foreign_key: "followed_id",
  #                                  class_name: "Relationship",
  #                                  dependent:  :destroy
  # has_many :followers, through: :reverse_relationships, source: :follower
  has_many :comments

  # before_save{|user| user.email = email.downcase}

  # VALID_EMAIL_REGEX = /\A[^@]+@[^@]+\z/
  # validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, 
  #                                   uniqueness: {case_sensitive:false}
  # validates :password, presence: true, length: {minimum: 6}
  # validates :password_confirmation, presence: true

  # validates :username, presence: true, length: {within: 8..20}
  
  validates_attachment :avatar, content_type: {content_type: ["image/jpeg", "image/png", 
                                                        "image/bmp", "image/jpg"]},
                                size: {less_than: 5.megabytes}
  

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           username: auth.info.nickname,
                           email:auth.info.email,
                           sex: auth.gender,
                           location: auth.info.location,
                           website: auth.link,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


### This is the correct method you override with the code above
### def self.find_for_database_authentication(warden_conditions)
### end 

  def feed
  	Story.from_users_followed_by(self)
  end

  def notify_follow(user)
    Notification.new(sender_id: self.id,
                       receiver_id: user.id,
                       notifiable_type: "new_follower").save 
  end

  def notify_unfollow(user)
    Notification.new(sender_id: self.id,
                       receiver_id: user.id,
                       notifiable_type: "unfollowed").save     
  end

  def notify_pending(user)
    Notification.new(sender_id: self.id,
                       receiver_id: user.id,
                       notifiable_type: "pending_user").save     
  end

  def notify_comment(story)
    old_alerts = Notification.where("receiver_id = #{story.user.id} AND
                                    sender_id = #{self.id} AND 
                                    notifiable_id = #{story.id} AND
                                    notifiable_type = 'comment'")
    if old_alerts.empty?
      Notification.new(sender_id: self.id,
                         receiver_id: story.user.id,
                         notifiable_id: story.id,
                         notifiable_type: "comment").save
    else
      old_alerts.each do |f|
        f.delete
      end
      Notification.new(sender_id: self.id,
                         receiver_id: story.user.id,
                         notifiable_id: story.id,
                         notifiable_type: "comment").save

    end
  end

  def notify_vote(story)
    old_alerts = Notification.where("receiver_id = #{story.user.id} AND
                                    sender_id = #{self.id} AND 
                                    notifiable_id = #{story.id} AND
                                    notifiable_type = 'vote'")
    if old_alerts.empty?
      Notification.new(sender_id: self.id,
                         receiver_id: story.user.id,
                         notifiable_id: story.id,
                         notifiable_type: "vote").save
    else
      old_alerts.each do |f|
        f.delete
      end
      Notification.new(sender_id: self.id,
                         receiver_id: story.user.id,
                         notifiable_id: story.id,
                         notifiable_type: "vote").save

    end    
  end

  def unseen_alerts
    self.alerts.where("seen = false").count
  end

  def reset_alerts
    self.alerts.each do |f| 
      f.seen = true
      f.save
    end
  end

  def alerts
    Notification.alerts_for_me(self)
  end
  # def to_param
  #   username
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      # @after_sign_in_url = after_sign_in_path_for(@user)
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      # render 'callback', :layout => false

      # # if params[:state] == 'popup'
      # #   render 'callback', :layout => false
      # # else
      # #   redirect_to @after_sign_in_url
      # # end
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	prepend_before_filter :authenticate_scope!, :only => [:edit, :update, :destroy, :password]

    def settings_password
    end

	def update
	    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
	 
	    # If the user has filled in any of the password fields, we'll update their password
	    any_passwords = %w(password password_confirmation current_password).any? do |field|
	      params[resource_name][field].present?
	    end
	    update_method = any_passwords ? :update_with_password : :update_without_password
	 
	    if resource.send(update_method, params[resource_name])
	      set_flash_message :notice, :updated if is_navigational_format?
	      sign_in resource_name, resource, :bypass => true
	      respond_with resource, :location => after_update_path_for(resource)
	    else
	      clean_up_passwords(resource)
	      respond_with_navigational(resource){ render :edit }
	    end
  	end
  
  	protected
      def after_update_path_for(resource)
        user_path(resource)
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!, only: [:index, :edit, :update, :destroy, :make_private, :make_public]
	before_filter :correct_user, only: [:edit, :update]
	before_filter :admin_user, only: :destroy

	def show
		@user = User.find(params[:id])
		@users = @user.following_users.paginate(page: params[:page])
		if @user == current_user
			@stories = Story.stories_from_me(@user.id).paginate(page: params[:page])
		else
			@stories = @user.stories.paginate(page: params[:page])
		end
	end

	def index
		@users = User.paginate(page: params[:page])
	end

	def search
		@users = User.user_search(params[:query]).paginate(page: params[:page])
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted"
		redirect_to :back
	end

	def following
	    @title = "Following"
	    @user = User.find(params[:id])
	    @users = @user.followed_users.paginate(page: params[:page])
	    render 'show_follow'
	end

	def followers
	    @title = "Followers"
	    @user = User.find(params[:id])
	    @users = @user.followers.paginate(page: params[:page])
	    render 'show_follow'
	end

	def follow
		@user = User.find(params[:id])
		current_user.follow(@user)
		# RecommenderMailer.new_follower(@user).deliver if @user.notify_new_follower
		redirect_to :back
		flash[:success] = "You are now following #{@user.username}."
		current_user.notify_follow(@user)
	end

	def unfollow
		@user = User.find(params[:id])
		current_user.stop_following(@user)
		redirect_to :back
		flash[:success] = "You are no longer following #{@user.username}."
		current_user.notify_unfollow(@user)
	end

	def unpend
		@user = User.find(params[:id])
		current_user.unpend(@user)
		redirect_to :back
		flash[:success] = "You are no longer following #{@user.username}."
		current_user.notify_pending(@user)
	end


	def make_private
		@user = User.find(params[:id])
		current_user.enable_privacy
		redirect_to :back
		flash[:notice] = "Your profile is now private"
	end

	def make_public
		@user = User.find(params[:id])
		current_user.disable_privacy
		redirect_to :back
		flash[:notice] = "Your profile is now public"
	end

	private

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_path) unless current_user?(@user)
		end

		def admin_user
			redirect_to(root_path) unless current_user.admin?
		end

end

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>

<div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= link_to "Unfollow", unfollow_user_path(@user), remote: true, :class => "btn btn-large" %>
  <% elsif current_user.pending?(@user) %>
  	<%= link_to "Pending", unfollow_user_path(@user), remote: true, :class => "btn btn-large" %>
  <% else %>
    <%= link_to "Follow", follow_user_path(@user), remote: true, :class => "btn btn-large btn-primary" %>
  <% end %>
</div>

<% end %>

app/views/users/_user.html.erb
<li>
	<span class="username">
		<%= link_to avatar_for(user, 'thumb'), user %>
	</span>

	<%= link_to user.username, user %>
	<%= user.admin %>

	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete,
						data: {confirm: "You sure?"} %>
	<% end %>
</li>

app/views/users/follow.html.erb
<%= form_for(follow_user_path(@user), remote: true) do |f| %>
	<%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/follow.js.erb
$('#follow_form').html('<%= escape_javascript(render :partial => "follow_form", :locals => {:user => @user}) %>');
$("#followers").html('<%= @user.followers.count %>');
$(".stories").html('<%= escape_javascript(render :partial => "story", :locals => (:user.story => @story)) %>');

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/make_private.html.erb
<%= link_to "make private", make_private_user_path, method: :get, :class => "btn btn-large btn-primary" %>

app/views/users/make_public.html.erb
<%= link_to "make public", make_public_user_path, method: :get, :class => "btn btn-large" %>

app/views/users/search.html.erb
<% provide(:title, 'All users') %>

<h1>Search results</h1>

<% if @users.any? %>

	<ul class="users">
		<%= render @users %>
	</ul>

	<%= will_paginate @users %>
<% else %>
	Could not find anything matching what you searched for.
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<section class="profile container">
  <div class="col-md-12 col-sm-12">
    <div class="row">
      <div class="col-md-4 col-sm-5 col-xs-12">
        <div class="panel panel-default">
          <%= link_to(image_tag(@user.avatar.url(:med)), @user.avatar.url(:med), :data => { :colorbox => true }, class: "panel-thumbail") unless @user.avatar.nil? %>
          <% if signed_in? %> 
              <% unless current_user?(@user) %>
                <div id="follow_form" class="panel-thumbnail">
                  <% if current_user.following?(@user) %>
                    <%= link_to "Unfollow", unfollow_user_path(@user), :class => "btn btn-large" %>
                  <% elsif current_user.pending?(@user) %>
                    <%= link_to "Pending", unpend_user_path(@user), :class => "btn btn-large" %>
                  <% else %>
                    <%= link_to "Follow", follow_user_path(@user), :class => "btn btn-large btn-primary" %>
                  <% end %>
                </div>
              <% end %>
            <% end %> 
        </div>
        <div class="panel">
          <div class="panel-body">
            <h2 class="mar-top10 mar-bot10 align-center"><%= @user.name %></h2>
            <hr>
            <%= render 'shared/stats' %>
          </div>
        </div>

        <div class="panel panel-default following-panel">
          <div class="panel-heading">
            <h4>Following</h4>
          </div>
          <% if @user.follows.any? %>
            <div class="panel-body">        
              <% @user.follows.each do |followed_user| %>
                <% user = User.find(followed_user.followable_id) %>
                <%= link_to avatar_for(user, 'xsml'), user_path(user) %>
              <% end %>
            </div> 
          <% end %>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading"><h3 class="mar-top10 mar-bot10">About</h3></div>
          <div class="panel-body about">
            <p><% if @user.sex.to_s == "male" %>
              <i class="fa fa-male"></i><%= @user.sex.to_s %>
            <% elsif @user.sex.to_s == "female" %>
              <i class="fa fa-female"></i><%= @user.sex.to_s %>
            <% end %>
            </p>
            <p><i class="fa fa-home"></i><%= @user.location %></p>
            <p><i class="fa fa-info"></i><%= @user.bio %></p></li>
          </div>         
        </div> 
      </div>

      <div class="col-md-6 col-sm-7 col-xs-12">
        <% if @user == current_user || !@user.private_followable? || current_user.following?(@user) %>
          <% if @user.stories.any? %>
            <ol class="stories">
              <%= render @user.stories %>
            </ol>
            <%= will_paginate @stories %>
          <% end %>    
        <% else %>
          <ol class="stories">
            <li>
              <h1>This is a private user</h1>
            </li>        
          </ol>
        <% end %>
      </div>

      <div class="col-md-3 hidden-sm hidden-xs"></div>
    </div>
  </div>
</section>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<div class="row">
	<aside class="span3">
		<span class="profile-pic">
	      <%= link_to(image_tag(@user.avatar.url(:med)), @user.avatar.url(:med), :data => { :colorbox => true }) unless @user.avatar.nil? %>
	      <h1>
	        <%= link_to @user.name, @user %>
	      </h1>
	    </span>      

	    <span class="profile-stats">
	      <%= render 'shared/stats' %>
	    </span>

	    <span class="profile-follow">
	      <% if @users.any? %>
	        <div class="user_avatars">
	          <% @users.each do |user| %>
	            <%= link_to avatar_for(user, 'xsml'), user %>
	          <% end %>
	        </div>
	      <% end %>
	    </span> 
	</aside>

	<div class="span8">
		<h3><%= @title %></h3>
		<% if @users.any? %>
				<ul class="users">
					<% @users.each do |user| %>
						<%= render partial: "follow_users", locals: {user: user} %>
					<% end %>
				</ul>
				<%= will_paginate %>
		<% end %>
	</div>
</div>

app/views/users/unfollow.html.erb
<%= form_for(unfollow_user_path(@user), remote:true) do |f| %>
	<%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/unfollow.js.erb
$('#follow_form').html('<%= escape_javascript(render :partial => "follow_form", :locals => {:user => @user}) %>');
$("#followers").html('<%= @user.followers.count %>');
$(".stories").html('<%= escape_javascript(render :partial => "story", :locals => {:user.story => @story}) %>');