config/routes.rb
Wir2::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations", 
                                      :omniauth_callbacks => "users/omniauth_callbacks"},
                     :path => '', :path_names => {:sign_in => "login", :sign_out => "logout",
                                                  :sign_up => "register"}

  devise_scope :user do
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "register", :to => "users/registrations#new"
    get "delete", :to => "users/registrations#destroy"
    get "settings", :to => "users/registrations#edit"
    get "settings/password", :to=> "users/registrations#password"
    get "settings/privacy", :to=> "users/registrations#privacy"
    get "search", :to=> "users#search"
    match '/search', to: 'users#search'
    get "profile", :to =>  "users#show"
  end 

  resources :users do
    member do
      get :follow
      get :unfollow
      get :unpend
      get :make_public
      get :make_private
    end
  end

  resources :notifications
  
  resources :pages
  resources :stories do
    member do
      get :vote_up
      get :vote_down
      get :unvote
      get :comment
    end
  end

  resources :comments
  resources :votes
  resources :relationships, only:[:create, :destroy]
  
  root :to => "pages#home"

  get '/about', to: 'pages#about'











end

app/views/shared/_comment_form.html.erb
<%= simple_form_for(@comment, remote: true, :validate => true, class: "panel") do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	
	<%= f.hidden_field :story_id, value: @story.id %>
	<%= f.text_area :comment, placeholder: "write a comment...", class: "comment-entry" %>
<% end %>

<script type="text/javascript">
	$('#comment_comment').keypress(function(e){
		if (e.which == 13) {
			$('form#new_comment').submit();
			return false;
		}
	});
</script>

app/views/shared/_comments.html.erb
<ol class="comments-list" id="comments-section">
	<% @story.comments.each do |comment| %>
		<li class="panel" id="<%= comment.id %>">
			<div class="panel-heading">
				<%= link_to avatar_for(comment.user, 'xsml'), comment.user, class: "panel-avatar" %><span class="comment-user"><%= link_to comment.user.username, user_path(comment.user) %>
				<% if current_user == comment.user %></span>
					<span class="delete-btn mar-top5" style="float:right;">
					 	<%= link_to comment, method: :delete do %>
							<i class="icon-remove"></i>
						<% end %>
					</span>
				<% end %>
			</div>
			<div class="panel-body">
				<%= comment.comment_html %>
				<hr>
				<div class="comment-time">
					<%= time_ago_in_words(comment.created_at) %> ago.
				</div>
			</div>
		</li>
	<% end %>
</ol>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% @feed_items = current_user.feed.paginate(page: params[:page]) %>

<% unless @feed_items.empty? %>
<ol class="stories">
	<%= render partial: 'shared/feed_item', collection: @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>


app/views/shared/_feed_item.html.erb
<li class="panel panel-default" id="<%= feed_item.id %>">
	
	<div class="panel-heading story-heading">
		<%= link_to avatar_for(feed_item.user, 'thumb'), feed_item.user, class: "panel-avatar" %>
		<span class="story-title"><%= link_to feed_item.title, story_path(feed_item) %></span>
		
		<span class="comment mar-top15">
			<%= link_to story_path(feed_item) do %><i class="fa fa-comment"></i><%= feed_item.comments.count %>
			<% end %>
		</span>
	</div>
	<div class="story-<%= feed_item.id %>" id="story">
		<% if feed_item.content_image? %>
			<span class="story-image">
				<%= image_tag feed_item.content_image.url(:small) %>
			</span>
		<% end %>

		<div class="panel-body">
			<span class="details mar-bot20">
				posted by: <%= link_to feed_item.user.username, feed_item.user %>
				<span class="timestamp">
					<%= time_ago_in_words(feed_item.created_at) %> ago.
				</span>
				<span class="delete mar-top15">
					<% if current_user.id == (feed_item.origin_user_id) %>
						<%= link_to feed_item, method: :delete,
												data: {confirm: "You sure!"},
												title: feed_item.title do %>
							delete
						<% end %>
					<% end %>
				</span>
			</span>
			<div class="mar-top20" id="story-content">
				<%= feed_item.content_html %>
			</div>
			<hr style="margin-bottom:0px;">
			<div class="vote-<%= feed_item.id %>">
				<%= render partial: "shared/vote", locals: {feed_item: feed_item} %>		
			</div>
			
		</div>
	</div>
</li>

<span class="comments-<%= feed_item.id %>">
</span>

app/views/shared/_login_form.html.erb
<div class="login">
	<%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
		<%= f.text_field :login, placeholder: 'Email/Username' %>
		<%= f.password_field :password, placeholder: 'Password' %>
		<%= f.input_field :remember_me, as: :boolean, inline_label: 'Remember me'%>		  
	  	<%= f.submit 'Sign in', class: "btn login-btn btn-primary"  %><br>
	  	<%= link_to "Forgot your password?", new_password_path('user'), class: "pull-left" %>	  	
	<% end %>
</div>

app/views/shared/_notifications.html.erb
<% if current_user.unseen_alerts == 0 %>
	<ul class="dropdown-menu">
		<li class="dropdown-links">You have no new notifications</li>
	</ul>
<% else %>
	<% if notifications?(current_user) %>
		<ul class="dropdown-menu">
		<% @notifications.limit(10).each do |notification| 
				sender = User.find(notification.sender_id) %>
			<li class="dropdown-links notifications"><%= auto_html(message(sender, notification)){link} %> <%= time_ago_in_words(notification.created_at) %> ago</li>
			<% end %>
		</ul>
	<% end %>		
<% end %>

app/views/shared/_signup_form.html.erb
<div class='signup'>
	<h2>Join the fun!</h2>
	<%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
    <%= devise_error_messages! %>
		<%= f.text_field :name, placeholder: 'Full Name' %>

		<%= f.text_field :email, placeholder: 'Email' %>

		<%= f.password_field :password, placeholder: 'Create a password' %>

		<%= f.password_field :password_confirmation, placeholder: 'Confirm password' %>
		<div class='pull-right'>
			<%= f.submit "Signup", class: "btn btn-large btn-primary" %>
		</div>
	  	
	<% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="profile-stats">
	<div class="followers col-md-4 col-sm-4 col-xs-4 align-center">
		<div>
			<%= @user.followers_count %>
		</div>
		<div>
			<%= "followers".pluralize(@user.followers_count) %>
		</div>
	</div>
	<div class="following col-md-4 col-sm-4 col-xs-4 align-center">
		<div>
			<%= @user.following_users_count %>
		</div>
		<div>
			<%= "following".pluralize(@user.following_users_count) %>
		</div>
	</div>
	<div class="story-count col-md-4 col-sm-4 col-xs-4 align-center">
		<div>
			<%= @user.stories.count %>
		</div>
		<div>
			<%=  "stories".pluralize(@user.stories.count) %>
		</div>
	</div>
</div>

app/views/shared/_story_form.html.erb
<%= simple_form_for(@story, remote: true, :validate => true, :html => { :multipart => true } ) do |f| %>
  <h4 class="mar-bot20">What's the Scoop</h4>
  
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">
    <%= f.text_field :title, placeholder: "Title" %>
  </div>

  <label class="checkbox mar-top10">
    <input id="story_anonymous" label="Post anonymously?" name="story[anonymous]" type="checkbox" value="1"> anonymous post?
  </label>

  <div class="field">
    <%= f.text_area :content, placeholder: "What do you want to say..." %>
  </div>

  <div class="row">
    <div class="col-md-2 col-sm-2 col-xs-2">
      <div class="btn btn-default btn-file ">
        <i class="glyphicon glyphicon-camera"></i> <%= f.file_field :content_image %>
      </div>
    </div>

    <div class="col-md-10 col-sm-10 col-xs-10 align-right">
      <%= f.submit "Post", class: "btn btn-primary submit-btn" %>
    </div>
  </div>  
<% end %>

app/views/shared/_user_info.html.erb
<div class="panel-thumbnail">
	<a href="<%= user_path(current_user) %>">
		<%= avatar_for(current_user, "med") %>
	</a>
</div>
<div class="panel-body">
	<h1 class="mar-top10 mar-bot10 align-center">
		<%= link_to current_user.username, user_path(current_user) %>
	</h1>
</div>	

app/views/shared/_vote.html.erb
<% if user_signed_in? && (feed_item.user == current_user || feed_item.user.private_followable == false || current_user.following?(feed_item.user)) %>
	<% if feed_item.voted_by?(current_user) %>
		<% if current_user.voted_for?(feed_item) %>
			<!-- If signed in and voted for -->
			<div class="vote-items">
				<div class="like">
					<%= link_to unvote_story_path(feed_item), class: "wir", style: "color: #46a546;  font-size: 16px;", remote: true do %>
						<i class="fa fa-thumbs-up"></i>
					<% end %>
				</div>
				<div class="stats"><%= render :partial => "shared/votecount", locals: {feed_item: feed_item}  %></div>
				<div class="dislike">
					<%= link_to vote_down_story_path(feed_item), class: "wiw", remote: true do %><i class="fa fa-thumbs-down"></i>
					<% end %>
				</div>
			</div>
		<% else %>
			<!-- If signed in & voted against -->
			<div class="vote-items">
				<div class="like">
					<%= link_to vote_up_story_path(feed_item), class: "wir", remote: true do %>
						<i class="fa fa-thumbs-up"></i>
					<% end %>
				</div>
				<div class="stats"><%= render :partial => "shared/votecount", locals: {feed_item: feed_item}  %></div>
				<div class="dislike">
					<%= link_to unvote_story_path(feed_item), class: "wiw", style: "color: #9d261d; font-size: 16px;", remote: true do %>
						<i class="fa fa-thumbs-down"></i>
					<% end %>
				</div>
			</div>
		<% end %>
	<% else %>
		<!-- If signed in but hasn't voted yet -->
		<div class="vote-items">
			<div class="like">
				<%= link_to vote_up_story_path(feed_item), class: "wir", remote: true do %>
					<i class="fa fa-thumbs-up"></i>
				<% end %>
			</div><div class="stats"><%= render :partial => "shared/votecount", locals: {feed_item: feed_item}  %>
			</div><div class="dislike">
				<%= link_to vote_down_story_path(feed_item), class: "wiw", remote: true do %>
					<i class="fa fa-thumbs-down"></i>
				<% end %>
			</div>
		</div>
	<% end %>
	<!-- For none signed in or users thats not following -->
<% else %>
	<div class="vote-items row">
		<div class="like">
			<%= link_to vote_up_story_path(feed_item), class: "wir" do %>
				<i class="fa fa-thumbs-up"></i>
			<% end %>
		</div><div class="stats">
			<%= render :partial => "shared/votecount", locals: {feed_item: feed_item}  %>
		</div><div class="dislike">
			<%= link_to vote_down_story_path(feed_item), class: "wiw" do %>
				<i class="fa fa-thumbs-down"></i>
			<% end %>
		</div>
	</div>
<% end %>

app/views/shared/_vote1.html.erb
<% if feed_item.user == current_user || feed_item.user.private_followable == false || current_user.following?(feed_item.user)%>
	<% if feed_item.voted_by?(current_user) %>
		<% if current_user.voted_for?(feed_item) %>
			<span class="vote-btn">
				<%= link_to unvote_story_path(feed_item), class: "wir", remote: true do %>
					<i class="icon-wir"></i>
					<% if feed_item.upcount > 0 %><%= feed_item.upcount %><% end %>
				<% end %>
			</span>
			<span class="vote-btn">
				<%= link_to vote_down_story_path(feed_item), class: "wiw", remote: true do %><i class="icon-wiw"></i>
					<% if feed_item.downcount > 0 %><%= feed_item.downcount %><% end %>
				<% end %>
			</span>
		<% else %>
			<span class="vote-btn">
				<%= link_to vote_up_story_path(feed_item), class: "wir", remote: true do %>
					<i class="icon-wir"></i>
					<% if feed_item.upcount > 0 %><%= feed_item.upcount %><% end %>
				<% end %>
			</span>
			<span class="vote-btn">
				<%= link_to unvote_story_path(feed_item), class: "wiw", remote: true do %>
					<i class="icon-wiw" style= "background-position: -16px 0px"></i>
					<% if feed_item.downcount > 0 %><%= feed_item.downcount %><% end %>
				<% end %>
			</span>
		<% end %>
	<% else %>
		<span class="vote-btn">
			<%= link_to vote_up_story_path(feed_item), class: "wir", remote: true do %>
				<i class="icon-wir"></i>
			<% end %><% if feed_item.downcount > 0 %><%= feed_item.downcount %><% end %>
		</span>
		<span class="vote-btn">
			<%= link_to vote_down_story_path(feed_item), class: "wiw", remote: true do %>
				<i class="icon-wiw"></i>
			<% end %><% if feed_item.downcount > 0 %><%= feed_item.downcount %><% end %>
		</span>
	<% end %>
<% else %>
	<% if feed_item.voted_by?(current_user) %>
		<% if current_user.voted_for?(feed_item) %>
			<%= link_to unvote_story_path(feed_item), class: "wir" do %><%= feed_item.upcount %>
				<i class="icon-wir" style= "background-position: -16px -16px"></i>
			<% end %><% if feed_item.downcount > 0 %><%= feed_item.downcount %><% end %>

			<%= link_to vote_down_story_path(feed_item), class: "wiw" do %>
				<%= feed_item.downcount %><i class="icon-wiw"></i>
			<% end %><% if feed_item.downcount > 0 %><%= feed_item.downcount %><% end %>

		<% else %>
			<%= link_to vote_up_story_path(feed_item), class: "wir" do %>
				<%= feed_item.upcount %><i class="icon-wir"></i>
			<% end %><% if feed_item.downcount > 0 %><%= feed_item.downcount %><% end %>

			<%= link_to unvote_story_path(feed_item), class: "wiw" do %>
				<%= feed_item.downcount %><i class="icon-wiw" style= "background-position: -16px 0px"></i>
			<% end %><% if feed_item.downcount > 0 %><%= feed_item.downcount %><% end %>
		<% end %>
	<% else %>
		<%= link_to vote_up_story_path(feed_item), class: "wir" do %>
			<%= feed_item.upcount %><i class="icon-wir"></i>
		<% end %><% if feed_item.downcount > 0 %><%= feed_item.downcount %><% end %>
		<%= link_to vote_down_story_path(feed_item), class: "wiw" do %><%= feed_item.downcount %><i class="icon-wiw"></i>
		<% end %><% if feed_item.downcount > 0 %><%= feed_item.downcount %><% end %>
	<% end %>
<% end %>

app/views/shared/_votecount.html.erb
<% if feed_item.votes_for == feed_item.votes_against %>
    <span class="votecount" style= "color: #666666; display:block;">score</span>
<% elsif feed_item.votes_for < feed_item.votes_against %>
    <span class="votecount" style= "color:#ca0000;  display:block; font-weight: bold;"><%= feed_item.votes_against - feed_item.votes_for %></span>
<% else %>
	<span class="votecount" style= "color:#46a546;  display:block; font-weight: bold;"><%= feed_item.votes_for - feed_item.votes_against %></span>
<% end %>

<%= subscribe_to("/#{current_user.id}/votes") %>
<% current_user.all_following.each do |subscriber| %>
    <%= subscribe_to("/#{subscriber.id}/votes") %>
<% end %>