config/routes.rb
Wir2::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations", 
                                      :omniauth_callbacks => "users/omniauth_callbacks"},
                     :path => '', :path_names => {:sign_in => "login", :sign_out => "logout",
                                                  :sign_up => "register"}

  devise_scope :user do
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "register", :to => "users/registrations#new"
    get "delete", :to => "users/registrations#destroy"
    get "settings", :to => "users/registrations#edit"
    get "settings/password", :to=> "users/registrations#password"
    get "settings/privacy", :to=> "users/registrations#privacy"
    get "search", :to=> "users#search"
    match '/search', to: 'users#search'
    get "profile", :to =>  "users#show"
  end 

  resources :users do
    member do
      get :follow
      get :unfollow
      get :unpend
      get :make_public
      get :make_private
    end
  end

  resources :notifications
  
  resources :pages
  resources :stories do
    member do
      get :vote_up
      get :vote_down
      get :unvote
      get :comment
    end
  end

  resources :comments
  resources :votes
  resources :relationships, only:[:create, :destroy]
  
  root :to => "pages#home"

  get '/about', to: 'pages#about'











end

app/views/pages/_welcome.html.erb
<div class="center row">
	<h1>welcome to whichizrite</h1>
	
	<h2>
		be heard! don't forget to download our app from itunes or the android store
	</h2>

	<p>
		The idea is simple. Click whichizrite to approve of content and click whichizwrong if you disagree with the content. Now that you know what we are about. Click the sign up button & be heard.		
	</p>

	<%= link_to "Sign up now!", register_path, class: "btn btn-large btn-primary" %>
</div>

app/views/pages/about.html.erb
<% provide(:title, 'about') %> 
<div class="container">
	<div class="center row">
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-body">
					 <%= auto_html('Hey! Checkout out: https://www.youtube.com/watch?feature=player_embedded&v=yUmSVcttXnI') { youtube; link(:target => 'blank') } %>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-body">
					Test2
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-body">
					Test3
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<% if signed_in? %>
	<section class="home container">
		<!-- main area -->
		<div class="col-md-12 col-sm-12">
			<div class="row">
				<div class="right col-md-4 col-sm-5 col-xs-12">
					<div class="panel panel-default user-info">			
						<%= render 'shared/user_info' %>
					</div>
					<div class="panel">
						<div class="panel-body align-center">
							<%= render 'shared/stats' %>
						</div>
					</div>			
				</div>
				<div class="main col-md-6 col-sm-7 col-xs-12">
					<div class="well">				
						<%= render 'shared/story_form' %>
					</div>
					<!-- <h1 class="feed-header">latest entries</h1> -->
					<div class="ajaxreloadstories">	
						<%= render 'shared/feed' %>
					</div>				
				</div>

				<div class="side col-md-2 hidden-sm hidden-xs">
					<div class="panel panel-default">
						<div class="panel-heading">
							<%= form_tag search_path, method: :get, :class => "user-search" do %>
				              <%= text_field_tag :query, params[:query], :placeholder => "Find Users", :value => '', :class => "user-query" %>
				            <% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- end main area -->
	</section>
<% else %>
<section class="home container">
	<div class="col-md-12 col-sm-12">
		<div class="row">
			<div class="hero-unit align-center">
				<h1>welcome to whichizrite</h1>
				
				<h2>
					be heard!
				</h2>

				<p>
					Our community empowers users to share news stories, ideas, gossip, stories or get opinions from users. Each story has a metric that is calculated by waging positive responses vs negative responses. Click the signup button to join the experience.	
				</p>
				<br>
				<%= link_to "Sign up now!", register_path, class: "btn btn-large btn-primary" %>
			</div>
		</div>
	</div>
</section>
<% end %>

app/views/pages/home.js.erb
$("li.dropdown-toggle").prepend("<%= escape_javascript(render partial: 'shared/feed_item', locals: {feed_item: @story}) %>");

app/views/pages/index.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="span4">
			<section>
				<%= render 'shared/story_form' %>
			</section>
		</aside>
		<div class="span8">
			<h3>Story feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>
<div class="center row">
	<h1>welcome to whichizrite</h1>
	
	<h2>
		be heard! don't forget to download our app from itunes or the android store
	</h2>

	<p>
		The idea is simple. Click whichizrite to approve of content and click whichizwrong if you disagree with the content. Now that you know what we are about. Click the sign up button & be heard.		
	</p>

	<%= link_to "Sign up now!", register_path, class: "btn btn-large btn-primary" %>
</div>
<% end %>