config/routes.rb
Wir2::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations", 
                                      :omniauth_callbacks => "users/omniauth_callbacks"},
                     :path => '', :path_names => {:sign_in => "login", :sign_out => "logout",
                                                  :sign_up => "register"}

  devise_scope :user do
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "register", :to => "users/registrations#new"
    get "delete", :to => "users/registrations#destroy"
    get "settings", :to => "users/registrations#edit"
    get "settings/password", :to=> "users/registrations#password"
    get "settings/privacy", :to=> "users/registrations#privacy"
    get "search", :to=> "users#search"
    match '/search', to: 'users#search'
    get "profile", :to =>  "users#show"
  end 

  resources :users do
    member do
      get :follow
      get :unfollow
      get :unpend
      get :make_public
      get :make_private
    end
  end

  resources :notifications
  
  resources :pages
  resources :stories do
    member do
      get :vote_up
      get :vote_down
      get :unvote
      get :comment
    end
  end

  resources :comments
  resources :votes
  resources :relationships, only:[:create, :destroy]
  
  root :to => "pages#home"

  get '/about', to: 'pages#about'











end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "home", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner nav-collapse">
    <div class="column">
      <%= link_to image_tag("wir_logo.png", alt: "logo"), root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <!-- <form class="navbar-search">
            <input type="text" class="search-query span3" >
            <div class="icon-search"></div>
          </form> -->
          <% if user_signed_in? %>
            <%= form_tag stories_path, method: :get, :class => "navbar-search" do %>
              <%= text_field_tag :query, params[:query], :placeholder => "search", :value => '', :class => "search-query span3" %>
              <div class="icon-search"></div>
            <% end %>
          <% end %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>          
          <% if user_signed_in? %>
            <li id="fat-menu" class="dropdown alerts">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= "#{pluralize( "(" + current_user.unseen_alerts.to_s + ")", "Alert")}" %><b class="caret"></b>
              </a>
              <%= render 'shared/notifications' %>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class="dropdown-links"><%= link_to "Profile", root_path %></li>
                <li class="dropdown-links"><%= link_to "Edit Profile", settings_path %></li>
                <li class="divider"></li>
                <li class="dropdown-links"><%= link_to "Users", users_path %></li>
                <li class="divider"></li>
                <li class="dropdown-links">
                  <%= link_to "Sign out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar_links.html.erb
<% if user_signed_in? %>
  <li class="dropdown alerts">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= "#{pluralize( "(" + current_user.unseen_alerts.to_s + ")", "Alert")}" %><i class="fa fa-exclamation-circle"></i>
    </a>
    <%= render 'shared/notifications' %>
  </li>
  
  <li class="dropdown-links"><%= link_to "Profile", root_path %></li>
  <li class="dropdown-links"><%= link_to "Edit Profile", settings_path %></li>
  <li class="divider"></li>
  <li class="dropdown-links"><%= link_to "Users", users_path %></li>
  <li class="divider"></li>
  <li class="dropdown-links">
    <%= link_to "Sign out", logout_path, method: "delete" %>
  </li>
  </li>
<% else %>
  <li><%= link_to "Sign in", login_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-green navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "whichizrite", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if signed_in? %>
	<form class="navbar-form navbar-left" action="/stories" method="get">
		<div class="input-group input-group-sm" style="max-width:360px;">
			<input type="text" class="form-control" placeholder="Search" name="query" id="srch-term">
			<div class="input-group-btn" value>
			  <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
			</div>
		</div>
	</form>
	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i></a>
	  <ul class="dropdown-menu">
	    <li><%= link_to "Profile", user_path(current_user) %></li>
	    <li><%= link_to "User Panel", settings_path %></li>
	    <li><%= link_to "Logout", logout_path %></li>
	  </ul>
	</li>
<% else %>
	<li><%= link_to "Login", login_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Wir2" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= subscribe_to("/#{current_user.id}/notifications") %>
      <% current_user.stories.each do |story| %>
          <%= subscribe_to("/#{story.id}/alerts") %>
      <% end %>
    <% end %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>